# Reading the data

In [9]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [10]:
caminho = r"C:/Users/Hychiro/Documents/Mestrado/Mestrado/Mestrado/Review/SLR-BCI-temporal-filters/structured_data/secondStepOutput.csv"

# Lê o CSV
df = pd.read_csv(caminho, encoding="utf-8")
print("Número de linhas e colunas:", df.shape)
df.head()

Número de linhas e colunas: (488, 17)

,Autores,Titulo,Ano de Publicacao,Fonte,Status,Review_Survey,EEG,BCI,MI,Classification,Model/pipeline,Temporal_filter,Anotation,Objective,Model_used,Temporal_filters_used,Datasets_used
0,A. D. Athapattu; P. S. B. Dassanayake; G. S. C...,Self-Paced Brain-Computer Interface on Sensori...,2024,IEEE,nao,nao,sim,sim,nao,sim,sim,sim,Não trabalha com MI,-,-,-,-
1,Z. Wang; C. Cao; Y. Zhou; L. Chen; B. Gu; S. L...,Integrating EEG and NIRS improves BCI performa...,2021,IEEE,nao,nao,sim,sim,sim,sim,sim,nao,O artigo usa filtro temporal no pre processame...,-,-,-,-
2,R. Govindarajan; M. Haritha; M. O. Sabri; B. P...,Optimal Deep Learning Model and Non-linear Fea...,2025,IEEE,nao,nao,sim,sim,nao,sim,sim,sim,"Artigo não usa MI, mas sim classifica estados ...",-,-,-,-
3,R. Jiang; S. Qiu; Y. Wang; C. Zhang; H. He,Evaluation of EEG and MEG responses during Fin...,2024,IEEE,nao,nao,sim,sim,sim,nao,nao,sim,Não é paradigma de classificação e portanto ne...,-,-,-,-
4,Z. Wang; L. Yang; Y. Zhou; L. Chen; B. Gu; S. ...,Incorporating EEG and fNIRS Patterns to Evalua...,2023,IEEE,nao,nao,sim,sim,sim,sim,sim,nao,Copia do artigo Integrating EEG and NIRS impro...,-,-,-,-

In [11]:
#todos as colunas Status do dataframe como "não" são retiradas
df_papers = df[df['Status'] != 'nao']
df_not_papaers = df[df['Status'] == 'nao']

df_reviewsOrSurveys = df[df['Review_Survey'] == 'sim']

print("Número de linhas e colunas após filtrar Status 'não':", df_papers.shape)
print("Número de linhas e colunas após filtrar Review_Survey 'sim':", df_reviewsOrSurveys.shape)
df_reviewsOrSurveys.head()

Número de linhas e colunas após filtrar Status 'não': (412, 17)
Número de linhas e colunas após filtrar Review_Survey 'sim': (4, 17)

,Autores,Titulo,Ano de Publicacao,Fonte,Status,Review_Survey,EEG,BCI,MI,Classification,Model/pipeline,Temporal_filter,Anotation,Objective,Model_used,Temporal_filters_used,Datasets_used
17,M. Iftikhar; S. A. Khan; A. Hassan,A Survey of Deep Learning and Traditional Appr...,2018,IEEE,nao,sim,sim,sim,sim,nao,nao,sim,O artigo é um Survey de metodos e modelos. Não...,survey na area,"não há, pois ele fala de muitos","fala de filtros temporais basicos (high, low e...",nao tem
44,Mishra S.; Mahmudi O.; Jalali A.,Motor Imagery Signal Classification Using Adve...,2024,Scopus,nao,sim,sim,sim,sim,nao,sim,sim,É uma review braba. Usar de referencia para fa...,-,-,-,-
280,Z. Shuqfa; A. Lakas,Motor Imagery–Based Brain–Computer Interfaces:...,2025,IEEE,nao,sim,sim,sim,sim,nao,nao,nao,Um survey da literatura,-,-,-,-
465,A. Zancanaro; G. Cisotto; J. R. Paulo; G. Pire...,CNN-based Approaches For Cross-Subject Classif...,2021,IEEE,sim,sim,sim,sim,sim,sim,sim,sim,é uma survey que analisa Abordagens CNN para E...,é uma survey que analisa abordagens cnn para e...,pipelines,"usa filtro pasa banda 4-40hz, tem o filterbank...","usa dataset bcicv2a: 59.35%, 67.88% e 72.5% ..."

In [12]:
# usar apenas colunas Autores	Titulo	Ano de Publicacao	Fonte	Anotation	Objective	Model_used	Temporal_filters_used	Datasets_used

df_final = df_papers[['Autores', 'Titulo', 'Ano de Publicacao', 'Fonte', 'Anotation', 'Objective', 'Model_used', 'Temporal_filters_used', 'Datasets_used']]

In [13]:
df_final.head()

,Autores,Titulo,Ano de Publicacao,Fonte,Anotation,Objective,Model_used,Temporal_filters_used,Datasets_used
5,M. J. Khan; K. -S. Hong; N. Naseer; M. R. Bhutta,A hybrid EEG-fNIRS BCI: Motor imagery for EEG ...,2014,IEEE,"Artigo esquisito, dataset só com 4 pessoas, fa...",mostrar nova abordagem eeg nirs para bci,"não tem um claro, mas usa para o eeg, bandpass...","bandpass, porem tem alguma chance do wavelet p...","dataset proprio, 4 sujeitos, commom state vs r..."
6,S. Zhu; S. I. Hosni; X. Huang; S. B. Borgheai;...,A Graph-Based Feature Extraction Algorithm Tow...,2021,IEEE,"Artigo completo, fala sobre uma abordagem EEG-...",proposta de um metodo de grafo para extração d...,"tem um pipeline bandpass, complex morlet waves...",bandpass e cmw,dataset proprio tendo as abordagens variando e...
7,Qin L.; Ding L.; He B.,Motor imagery classification by means of sourc...,2004,Scopus,"Artigo completo, fala sobre uso de filtro temp...",test the hypothesis that the source analysis m...,"laplaciano, bandpass usano fifth-order butterw...",bandpass usano fifth-order butterworth,the eeg data consisting of synchronized imagin...
8,Yamaguchi T.; Fujio M.; Inoue K.,Design method of morphological structuring fun...,2011,Scopus,"O artigo possui um sistema unico, onde o filtr...","propoe usar a uma estrategia ""morphological mu...",somente algoritmos proprios para todo o processo,uma especie de filtro temporal adaptativo base...,"dataset proprio de 3 individuos, tem feedback ..."
9,Higashi H.; Tanaka T.,Common spatio-time-frequency patterns for moto...,2013,Scopus,O artigo propoe um metodo novo que aparenta ba...,propoe um metodo novo cstfp,cstfp,"filtros fir imbutidos dentro do cstfp, butterw...","bci c iii iva -> csp: 87.9, csp-exh: 91.3, css..."

In [14]:
#passar para um arquivo CSV
df_final.to_csv('C:/Users/Hychiro/Documents/Mestrado/Mestrado/Mestrado/Review/SLR-BCI-temporal-filters/structured_data/final_output.csv', index=False, encoding='utf-8-sig')
df_not_papaers.to_csv('C:/Users/Hychiro/Documents/Mestrado/Mestrado/Mestrado/Review/SLR-BCI-temporal-filters/structured_data/not_papers_output.csv', index=False, encoding='utf-8-sig')

### Prints

In [15]:
#loop para verificar cada linha do df_final printando nome do artigo e o filtro temporal usado.
flag = True
while flag:
    for index, row in df_final.iterrows():
        print("Artigo:", row['Titulo'])
        print("Filtro temporal usado:", row['Temporal_filters_used'])
        print("--------------------------------------------------")
    flag = False

Artigo: A hybrid EEG-fNIRS BCI: Motor imagery for EEG and mental arithmetic for fNIRS
Filtro temporal usado: bandpass, porem tem alguma chance do wavelet poder ser encaixado aqui também. o artigo não deixa claro pois fala (" the wavelet transform was  used  to  distinguish  the  imagery  states")
--------------------------------------------------
Artigo: A Graph-Based Feature Extraction Algorithm Towards a Robust Data Fusion Framework for Brain-Computer Interfaces
Filtro temporal usado: bandpass e cmw
--------------------------------------------------
Artigo: Motor imagery classification by means of source analysis for brain-computer interface applications
Filtro temporal usado: bandpass usano fifth-order butterworth
--------------------------------------------------
Artigo: Design method of morphological structuring function for pattern recognition of EEG signals during motor imagery and cognition
Filtro temporal usado: uma especie de filtro temporal adaptativo baseado em high e low pass. é uma decomposição do sinal seguindo como se fosse um wavelet. mas no fim resulta em um passa baixa um passa alta e 2 passa bandas criando 4 intervalos.
--------------------------------------------------
Artigo: Common spatio-time-frequency patterns for motor imagery-based brain machine interfaces
Filtro temporal usado: filtros fir imbutidos dentro do cstfp, butterworth bandpass filter with the passband of 7–30 hz (csp), passband of the butterworth tunada com busca exausitva (csp-exh), bandpass filter between 7 and 30 hz (csssp, deve ser butterworth), filterbank usando chebyshev ii indo 4 a 4 de 4-40 (fbcsp), filtro fir de ordem 41 (possivel otimização, dfbcsp)
--------------------------------------------------
Artigo: A2FWPO: Anti-aliasing Filter Based on Whale Parameter Optimization Method for Feature Extraction and Recognition of Dance Motor Imagery EEG
Filtro temporal usado: filtro temporal band pass teoricamente, filtro temporal anti-aliasing para separar em sub bandas (2 pelo que entendi)
--------------------------------------------------
Artigo: A multi-modal BCI system based on motor imagery
Filtro temporal usado: decomposição por wpd ou db4w pelo que entendi
--------------------------------------------------
Artigo: Multivariate Adaptive Autoregressive Modeling and Kalman Filtering for Motor Imagery BCI
Filtro temporal usado: bandpass de 9 a 30hz
--------------------------------------------------
Artigo: Analysis of EEG signal evoked by passive movement and motor imagery
Filtro temporal usado: filter bank 8 a 32
--------------------------------------------------
Artigo: Hybrid mental tasks based human computer interface via integration of pronunciation and motor imagery
Filtro temporal usado: band pass e possivelmente um metodo adaptativo para encontrar as bandas do sfbcsp (dentro do intervalo de 8 a 30hz)
--------------------------------------------------
Artigo: Wavelet analysis of EEG signals during motor imagery
Filtro temporal usado: band-pass 1.5–60 hz, wavelet (cspline e daubechies), morphological wavelet filters (haar-type morphology-> decomposição do sinal)
--------------------------------------------------
Artigo: iTa-DFiE: An Innovative Tensor Algebra-Based Detection Framework for Incomplete Noninvasive Electroencephalography
Filtro temporal usado: integrado no kalman filter (faz "capture simultaneously smoothness and correlation in eeg time series automatically")
--------------------------------------------------
Artigo: Time-frequency analysis of EEG signals from healthy subjects allocated by gender for a subject-independent BCI-based on motor imagery
Filtro temporal usado: fft, wavelet, bandstop, high e low pass
--------------------------------------------------
Artigo: Feature selection strategy for classification of single-trial EEG elicited by motor imagery
Filtro temporal usado: bandpass e dwt (wavelet).
--------------------------------------------------
Artigo: CD3Net: A Contrastive Diffusion Model with Domain Adaptive Data Synthetic Network for Motor Imagery and Emotion classification
Filtro temporal usado: integrado na rede
--------------------------------------------------
Artigo: A Deep Learning Scheme for Motor Imagery Classification based on Restricted Boltzmann Machines
Filtro temporal usado: butterworth 8 a 35hz
--------------------------------------------------
Artigo: An enhanced time-frequency-spatial approach for motor imagery classification
Filtro temporal usado: butterworth para separa 13 fequencias de 6 a 30hz
--------------------------------------------------
Artigo: Efficient Ocular Artifacts Removal From EEG Recordings Using State-Space Model
Filtro temporal usado: tecnicamente o filterbank do fbcsp que usa chebchev ii e tecnicamente o modulo ess da rede também realiza uma filtragem temporal.
--------------------------------------------------
Artigo: Statistical Wavelets With Harmony Search- Based Optimal Feature Selection of EEG Signals for Motor Imagery Classification
Filtro temporal usado: butterworth 0.5 a 100hz e dwt (wavelet -5 lv)
--------------------------------------------------
Artigo: Emotion-Inducing Imagery Versus Motor Imagery for a Brain-Computer Interface
Filtro temporal usado: acredito poder generalizar em bandpass, no caso do fbcsp usa chebyshev ii para o filterbank. os outros não explicita.
--------------------------------------------------
Artigo: EEG signal processing: Feature extraction, selection and classification methods
Filtro temporal usado: filterbank 4-40hz de chebychev ii ou selecionando bandas de frequencia do filterbank.
--------------------------------------------------
Artigo: Flexible coding scheme for robotic arm control driven by motor imagery decoding
Filtro temporal usado: camada de convolução temporal, wavelet (wwt) e empirical mode decomposition (emd).
--------------------------------------------------
Artigo: Classification scheme for arm motor imagery
Filtro temporal usado: os metodos de comparação fbcsp,csp e band power usam filtro fir ou filterbank (fbcsp).
--------------------------------------------------
Artigo: Adaptive modelling of eeg signals to produce accurate time-frequency decompositions for use in BCI
Filtro temporal usado: filtro fir de ordem 500 de 6 a 14hz.
--------------------------------------------------
Artigo: A study on the efficient tracking of ERD based on the adaptive identification of the subject's reactive band
Filtro temporal usado: fir ordem 500 6 a 14hz
--------------------------------------------------
Artigo: Effects of Trial-Adjusted Neurofeedback Training on Motor-Imagery Based Brain-Computer Interface Performance
Filtro temporal usado: filtro passa banda (0.5-40hz)
--------------------------------------------------
Artigo: An Effect of Limb Position in Motor Imagery Training Paradigm in Immersive Virtual Environment
Filtro temporal usado: filterbank do fbcsp  e talvez filtro passa banda 1 a 40hz no sinal bruto inicial.
--------------------------------------------------
Artigo: Motor-Related EEG Analysis Using a Pole Tracking Approach
Filtro temporal usado: butterworth 4th ordem para as filtragens bandpass 0.5-45hz, high-pass 5hz e low-pass 3hz. podemos contar os filtros intrínsecos ao metodo também
--------------------------------------------------
Artigo: Enhanced BCI Performance using Diffusion Model for EEG Generation
Filtro temporal usado: bandpass 8-26hz
--------------------------------------------------
Artigo: Simultaneous design of FIR filter banks and spatial patterns for EEG signal classification
Filtro temporal usado: filterbank do fbcsp separando 4 a 40hz com intervalos de 2,4 e 6hz. fir gerado pelos metodos dfbcsp e csssp. filtragem temporal presente dentro do cssp. butterworth passa banda 7-30hz de ordem 4.
--------------------------------------------------
Artigo: Adaptive spiking convolutional network for decoding motor imagery patterns
Filtro temporal usado: camada de convolução temporal
--------------------------------------------------
Artigo: Research on Motor Imagery Signal Recognition Method Based on Wavelet Packet Transform and ConvLSTM
Filtro temporal usado: filtro high pass, low pass (bandpass) 1hz e 50hz respectivamente. também corta sinal em 60hz. wavelet package também como filtro temporal
--------------------------------------------------
Artigo: Trust and explainability in robotic hand control via adversarial multiple machine learning models with EEG sensor data fusion: A fuzzy decision-making solution
Filtro temporal usado: butterworth 8-30hz e decomposição wavelet
--------------------------------------------------
Artigo: A Region of Interest-Based Electrophysiological Source Imaging Technology and its Applications in Analysis of Motor Imagery EEG Signals
Filtro temporal usado: butterworth 8-30hz. filterbank do fbcsp (não define se fez alteração nele)
--------------------------------------------------
Artigo: Feature bands study of MI signals based on FBCSP for CNN
Filtro temporal usado: filtos passa banda,  hilbert transformation tamanho 40hz, e filtro passa baixa 2hz e 10 bandpass de tamanho 4hz que ao retirar a parte complexa fica 2hz.
--------------------------------------------------
Artigo: Classification of EEG Signals Using a Common Spatial Pattern Based Motor-Imagery for a Lower-limb Rehabilitation Exoskeleton
Filtro temporal usado: iir 2 a 40hz e stop-band 50-60hz
--------------------------------------------------
Artigo: State-of-the-Art Versus Deep Learning: A Comparative Study of Motor Imagery Decoding Techniques
Filtro temporal usado: passa banda 1-40hz
--------------------------------------------------
Artigo: Enhanced Online Continuous Brain-Control by Deep Learning-Based EEG Decoding
Filtro temporal usado: filterbank do fbcsp com varios passa banda, 2 passabandas 4-16hz e 16-40hz no ifnet, junto de todas as camadas de convolução temporal nos modelos nn.
--------------------------------------------------
Artigo: Optimal design of a bank of spatio-temporal filters for EEG signal classification
Filtro temporal usado: filtro fir gerado pelo algoritmo para cada sujeito. foi especificao pelo menos que coefficientes fora do range de 7-30hz eram 0
--------------------------------------------------
Artigo: Smart thoughts: BCI based system implementation to detect motor imagery movements
Filtro temporal usado: filtro passa banda para 8-14hz, 19-24hz e 24-30hz para uma abordagem ou se não 7-30hz para a outra abordagem usada
--------------------------------------------------
Artigo: Discrimination of motor imagery patterns by electroencephalogram phase synchronization combined with frequency band energy
Filtro temporal usado: filtro passa banda 8-30hz
--------------------------------------------------
Artigo: Real-Time Motor Imagery-Based Brain–Computer Interface System by Implementing a Frequency Band Selection
Filtro temporal usado: filtro passa banda 15-26hz
--------------------------------------------------
Artigo: Classification of motor imagery by means of cortical current density estimation and Von Neumann entropy
Filtro temporal usado: filtro passa banda 8-12hz
--------------------------------------------------
Artigo: Research on Movement Intentions of Human's Left and Right Legs Based on Electro-Encephalogram Signals
Filtro temporal usado: filtro passa baixa 30hz e notch 50-60hz como filtro temporal
--------------------------------------------------
Artigo: Adaptive subject-based feature extraction in brain-computer interfaces using wavelet packet best basis decomposition
Filtro temporal usado: wavelet packet transform usando daubechies 4
--------------------------------------------------
Artigo: BCI Competition 2003 - Data set III: Modeling of sensorimotor μ rhythms for classification of imaginary hand movements
Filtro temporal usado: morlet wavelts focando em torno de 10hz e 20hz.
--------------------------------------------------
Artigo: Comparative analysis of spectral approaches to feature extraction for EEG-based motor imagery classification
Filtro temporal usado: metods de wavelet, stft e s transformation aparentam fazer decomposições no sinal em sub bandas selecionando as bandas mu(8-12hz) e beta(18-25hz)
--------------------------------------------------
Artigo: EEG pattern recognition: An efficient improvement combination of ERD/ERS/Laterality features to create a self-paced BCI system
Filtro temporal usado: artigo tem low pass filter fir (não fala de quanto) e stft parece ser aplicado como filtro temporal separando as bandas (mas tenho medo de falar se é isso mesmo).
--------------------------------------------------
Artigo: Supervised Relevance Analysis for Multiple Stein Kernels for Spatio-Spectral Component Selection in BCI Discrimination Tasks
Filtro temporal usado: filtro passa banda para criar um banco de filtros e msk para selecionar as bandas.
--------------------------------------------------
Artigo: Classification of imagery motor EEG data with wavelet denoising and features selection
Filtro temporal usado: bandpass butter worth e wavelet soft-threshold denoise
--------------------------------------------------
Artigo: EEG classification of different imaginary movements within the same limb
Filtro temporal usado: filtro passa banda frequencias 7-30hz (csp e bp) e 7–15 hz, 15–25 hz, 25–30 hz (fbcsp).
--------------------------------------------------
Artigo: Structure constrained semi-nonnegative matrix factorization for EEG-based motor imagery classification
Filtro temporal usado: filtro passa banda 8-35hz
--------------------------------------------------
Artigo: Two Class Motor Imagery Classification Based on ANFIS
Filtro temporal usado: dwt para decompor sinal em sub bandas
--------------------------------------------------
Artigo: Implementation of nonlinear classifiers for adaptive autoregressive EEG features classification
Filtro temporal usado: filtro high pass 2hz
--------------------------------------------------
Artigo: An empirical mode decomposition based filtering method for classification of motor-imagery EEG signals for enhancing brain-computer interface
Filtro temporal usado: emd decompondo e selecionando frequencia 6-26hz
--------------------------------------------------
Artigo: Motor imagery classification using feature relevance analysis: An Emotiv-based BCI system
Filtro temporal usado: emd e varias wavelets para selecionar bandas de frequencias mu e beta pela decomposiçao
--------------------------------------------------
Artigo: Envelope detection based on online ICA algorithm and its application to motor imagery classification
Filtro temporal usado: filtro pasa banda 8-14hz
--------------------------------------------------
Artigo: An adaptive EEG filtering approach to maximize the classification accuracy in motor imagery
Filtro temporal usado: 6 filtros temporais fir e iir diferentes com configurações diferentes dependendo do valor snr (fir:equiripple fir:kaiserwin iir:butterworth iir:chebyshev1 iir:chebyshev2 iir:elliptic)
--------------------------------------------------
Artigo: Maximum dependency and minimum redundancy-based channel selection for motor imagery of walking EEG signal detection
Filtro temporal usado: usa chebychev ii para fazer um banco de filtros 4-44hz de tamanho de banda 4hz e 2hz de overlap
--------------------------------------------------
Artigo: Feature extraction and visualization of MI-EEG by LLE algorithm
Filtro temporal usado: artigo usa db5 wavelet  daubechies  3-level  pra  decompor o sinal e selecionar ritmos alpha (8-13hz) e bbeta(14-30hz).
--------------------------------------------------
Artigo: Real-time single channel EEG motor imagery based Brain Computer Interface
Filtro temporal usado: filtro temporal usado é butterworth 4th ordem 1-35hz
--------------------------------------------------
Artigo: Joint spatial-temporal filter design for analysis of motor imagery EEG
Filtro temporal usado: filtro passa banda 8-35hz
--------------------------------------------------
Artigo: Motor imagery classification by means of source analysis methods
Filtro temporal usado: filtro passa banda 11-12hz
--------------------------------------------------
Artigo: Enhancement of Performance of an EEG-based Brain-Computer Interface by means of a Time-Frequency Approach
Filtro temporal usado: usa filtro butterworth passa banda 4th ordem para decompor componentes dem bandas de mesmo tamanho no intervalo 6-30hz.
--------------------------------------------------
Artigo: Study of On-Line Adaptive Discriminant Analysis for EEG-Based Brain Computer Interfaces
Filtro temporal usado: sa bandpass 10-12hz e 16-24hz
--------------------------------------------------
Artigo: Algorithm of Imagined Left-Right Hand Movement Classification Based on Wavelet Transform and AR Parameter Model
Filtro temporal usado: wavelets para decompor sinal
--------------------------------------------------
Artigo: Classifying Single-Trial EEG During Motor Imagery by Iterative Spatio-Spectral Patterns Learning (ISSPL)
Filtro temporal usado: usa filtro passa banda 7-30hz
--------------------------------------------------
Artigo: Classifying motor imagery EEG by Empirical Mode Decomposition based on spatial-time-frequency joint analysis approach
Filtro temporal usado: usa emd para decompor o sinal e usa time-varying rhythmic component description para recompor ele como um filterbank de 4 ritmos de eeg
--------------------------------------------------
Artigo: A Study on the impact of spectral variability in brain-computer interface
Filtro temporal usado: filtro fir (chamado modal filter) determinado pelas bandas de freqencia selecionadas do fisher ratio do mapa tempo frequencia de 1 eletrodo.
--------------------------------------------------
Artigo: Dynamic initiation and dual-tree complex wavelet feature-based classification of motor imagery of swallow EEG signals
Filtro temporal usado: filter bank do fbcsp que usa varios filtros passa banda
--------------------------------------------------
Artigo: Novel feature generation and classification for a 2-state Self-paced Brain Computer Interface system
Filtro temporal usado: memd para decompor sinal e filtro low pass 30hz
--------------------------------------------------
Artigo: A motor imagery BCI experiment using wavelet analysis and spatial patterns feature extraction
Filtro temporal usado: wavelet para decomposição do sinal
--------------------------------------------------
Artigo: Optimal segments selection for EEG classification
Filtro temporal usado: wavelet para decompor sinal
--------------------------------------------------
Artigo: EEG denoising with a recurrent quantum neural network for a brain-computer interface
Filtro temporal usado: rqnn
--------------------------------------------------
Artigo: Spatio-Temporal Joint Filtering for Transfer Learning in Brain-Computer Interface of Motion Imaginery
Filtro temporal usado: filtro fir de ordem 50 com passa banda 8-30hz e propôe um spatio-temporal joint filter otimizado de forma iterativa que possui ordem 100.
--------------------------------------------------
Artigo: Improving classification accuracy for motor imagery BCI using DWT based Features
Filtro temporal usado: usa 2th ordem do filtro butterworth como passa banda 12-29hz. usa dwt para decompor o sinal em 3 levels.
--------------------------------------------------
Artigo: Development of an Adaptive Artifact Subspace Reconstruction Based on Hebbian/Anti-Hebbian Learning Networks for Enhancing BCI Performance
Filtro temporal usado: filtro iir dentro do asr e bandpass de 8-50hz caso o uso desse filtro não tenha vindo direto do dataset.
--------------------------------------------------
Artigo: Features Extraction Technique Analysis of EEG Signal for Motor Imagery Classification

In [16]:
print("Datasets_used unique values:", df_datasets_used)

NameError: name 'df_datasets_used' is not defined